<a href="https://colab.research.google.com/github/dmitrijg08/MN/blob/main/%D0%93%D1%83%D1%81%D0%B0%D0%BA_%D0%94_%D0%9E_3_9_%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
# Код студента
import numpy as np

print(np.__version__)

2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [8]:
# Код студента
my_array = np.array([2, 4, 6, 8, 10])

print(my_array)
print(type(my_array))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [9]:
# Код студента
# Масив із 10 нулів
zeros_array = np.zeros(10)

# Масив із 8 одиниць
ones_array = np.ones(8)

# Масив із 6 елементів, усі значення яких дорівнюють 7
sevens_array = np.full(6, 7)

print("Масив нулів:", zeros_array)
print("Масив одиниць:", ones_array)
print("Масив сімок:", sevens_array)

Масив нулів: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Масив одиниць: [1. 1. 1. 1. 1. 1. 1. 1.]
Масив сімок: [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [10]:
# Код студента
# Масив цілих чисел від 1 до 20 включно
array_1_to_20 = np.arange(1, 21)

# Масив парних чисел від 2 до 20
even_array = np.arange(2, 21, 2)

print("Масив від 1 до 20:", array_1_to_20)
print("Масив парних чисел:", even_array)

Масив від 1 до 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Масив парних чисел: [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [11]:
# Код студента
# Масив із 11 рівновіддалених чисел від 0 до 1 включно
linspace_array = np.linspace(0, 1, 11)

print(linspace_array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [12]:
# Код студента
# Створення одновимірного масиву від 1 до 12
array_1d = np.arange(1, 13)

# Зміна форми на матрицю 3 × 4
matrix_3x4 = array_1d.reshape(3, 4)

print(matrix_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [13]:
# Код студента
print("Кількість вимірів (ndim):", matrix_3x4.ndim)
print("Форма (shape):", matrix_3x4.shape)
print("Загальна кількість елементів (size):", matrix_3x4.size)
print("Тип даних елементів (dtype):", matrix_3x4.dtype)

Кількість вимірів (ndim): 2
Форма (shape): (3, 4)
Загальна кількість елементів (size): 12
Тип даних елементів (dtype): int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [14]:
# Код студента
float_array = np.array([1.2, 3.5, 5.7, 7.9])

# Перетворення елементів на цілі числа
int_array = float_array.astype(int)

print(int_array)

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [15]:
# Код студента
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Перший елемент:", arr[0])
print("Останній елемент:", arr[-1])
print("Елементи з індексами від 2 до 5 включно:", arr[2:6])
print("Кожен другий елемент:", arr[::2])

Перший елемент: 10
Останній елемент: 80
Елементи з індексами від 2 до 5 включно: [30 40 50 60]
Кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [16]:
# Код студента
matrix = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]
])

print("Елемент 7:", matrix[1, 2])
print("Другий рядок:", matrix[1])
print("Третій стовпець:", matrix[:, 2])
print("Підматриця (останні 2 рядки, перші 2 стовпці):\n", matrix[1:, :2])

Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця (останні 2 рядки, перші 2 стовпці):
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [17]:
# Код студента
arr_1_to_15 = np.arange(1, 16)

# Заміна елементів з індексами від 5 до 9 (включно) на 0
# Оскільки зріз [5:10] не включає правий край, він охопить саме індекси 5, 6, 7, 8, 9
arr_1_to_15[5:10] = 0

print(arr_1_to_15)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [19]:
# Код студента
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Додавання (a + b):", a + b)
print("Віднімання (a - b):", a - b)
print("Множення (a * b):", a * b)
print("Ділення (a / b):", a / b)

Додавання (a + b): [11 22 33 44 55]
Віднімання (a - b): [ -9 -18 -27 -36 -45]
Множення (a * b): [ 10  40  90 160 250]
Ділення (a / b): [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [20]:
# Код студента
arr = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(arr))
print("Середнє значення:", np.mean(arr))
print("Мінімум:", np.min(arr))
print("Максимум:", np.max(arr))
print("Медіана:", np.median(arr))
print("Стандартне відхилення:", np.std(arr))

Сума: 108
Середнє значення: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [21]:
# Код студента
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Сума всіх елементів:", np.sum(matrix))
print("Сума по кожному стовпцю (axis=0):", np.sum(matrix, axis=0))
print("Сума по кожному рядку (axis=1):", np.sum(matrix, axis=1))
print("Середнє значення по кожному стовпцю (axis=0):", np.mean(matrix, axis=0))

Сума всіх елементів: 45
Сума по кожному стовпцю (axis=0): [12 15 18]
Сума по кожному рядку (axis=1): [ 6 15 24]
Середнє значення по кожному стовпцю (axis=0): [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [22]:
# Код студента
arr = np.arange(1, 11)

print("Квадрат кожного елемента:\n", np.square(arr))
# Також можна використати: arr ** 2 або np.power(arr, 2)

print("\nКвадратний корінь кожного елемента:\n", np.sqrt(arr))

print("\nНатуральний логарифм кожного елемента:\n", np.log(arr))

Квадрат кожного елемента:
 [  1   4   9  16  25  36  49  64  81 100]

Квадратний корінь кожного елемента:
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

Натуральний логарифм кожного елемента:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [23]:
# Код студента
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("Більші за 15:", arr[arr > 15])

print("Парні числа:", arr[arr % 2 == 0])

# Використовуємо побітове "І" (&) для об'єднання умов у круглих дужках
print("Від 10 до 30 включно:", arr[(arr >= 10) & (arr <= 30)])

Більші за 15: [18 21 25 30 34]
Парні числа: [12 18 30 34]
Від 10 до 30 включно: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [24]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])

# Заміна всіх від'ємних значень на 0
arr[arr < 0] = 0

print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [25]:
# Код студента
# Встановлення seed для відтворюваності результатів
np.random.seed(42)

# Створення масиву з 20 випадкових цілих чисел від 0 до 100 (включно)
arr = np.random.randint(0, 101, size=20)

print("Масив:", arr)

# Підрахунок елементів за допомогою сумування булевих значень (True = 1, False = 0)
count_greater = np.sum(arr > 50)
count_less_equal = np.sum(arr <= 50)

print("Кількість елементів, більших за 50:", count_greater)
print("Кількість елементів, менших або дорівнюють 50:", count_less_equal)

Масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Кількість елементів, більших за 50: 12
Кількість елементів, менших або дорівнюють 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [26]:
# Код студента
arr = np.arange(1, 25)

# Перетворення у матрицю 4 × 6
matrix_4x6 = arr.reshape(4, 6)
print("Форма 4 × 6:", matrix_4x6.shape)

# Перетворення у матрицю 6 × 4
matrix_6x4 = arr.reshape(6, 4)
print("Форма 6 × 4:", matrix_6x4.shape)

# Перетворення у тривимірний масив 2 × 3 × 4
array_3d = arr.reshape(2, 3, 4)
print("Форма 2 × 3 × 4:", array_3d.shape)

Форма 4 × 6: (4, 6)
Форма 6 × 4: (6, 4)
Форма 2 × 3 × 4: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [27]:
# Код студента
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# Вертикальне об'єднання
vertical_concat = np.vstack((A, B))
# Також можна використати: np.concatenate((A, B), axis=0)

# Горизонтальне об'єднання
horizontal_concat = np.hstack((A, B))
# Також можна використати: np.concatenate((A, B), axis=1)

print("Вертикальне об'єднання:\n", vertical_concat)
print("\nГоризонтальне об'єднання:\n", horizontal_concat)

Вертикальне об'єднання:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Горизонтальне об'єднання:
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [28]:
# Код студента
matrix = np.arange(1, 13).reshape(3, 4)
print("Оригінальна матриця:\n", matrix)

# Спосіб 1: flatten() - повертає КОПІЮ масиву
arr_flatten = matrix.flatten()

# Спосіб 2: ravel() - повертає ПРЕДСТАВЛЕННЯ (view) масиву, якщо це можливо
arr_ravel = matrix.ravel()

print("\nРезультат flatten():", arr_flatten)
print("Результат ravel():", arr_ravel)

# Порівняння: подивимось, що станеться, якщо змінити елементи в нових масивах
arr_flatten[0] = 99  # Змінюємо перший елемент у flatten (це копія)
arr_ravel[1] = 99    # Змінюємо другий елемент у ravel (це view)

print("\nОригінальна матриця після змін у flatten та ravel:\n", matrix)

Оригінальна матриця:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Результат flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Результат ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Оригінальна матриця після змін у flatten та ravel:
 [[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [29]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

# Сума векторів
vector_sum = a + b

# Різниця векторів
vector_diff = a - b

# Множення на число 3
a_mul_3 = a * 3
b_mul_3 = b * 3

print("Сума векторів:", vector_sum)
print("Різниця векторів:", vector_diff)
print("Вектор a помножений на 3:", a_mul_3)
print("Вектор b помножений на 3:", b_mul_3)

Сума векторів: [ 3  7 11]
Різниця векторів: [1 1 1]
Вектор a помножений на 3: [ 6 12 18]
Вектор b помножений на 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [30]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Спосіб 1: за допомогою np.dot()
dot_1 = np.dot(a, b)

# Спосіб 2: за допомогою оператора @
dot_2 = a @ b

print("Скалярний добуток (np.dot):", dot_1)
print("Скалярний добуток (оператор @):", dot_2)

Скалярний добуток (np.dot): 32
Скалярний добуток (оператор @): 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [31]:
# Код студента
v = np.array([3, 4])

# Евклідова норма вектора
norm_v = np.linalg.norm(v)

# Нормалізація вектора (ділення вектора на його норму)
normalized_v = v / norm_v

print("Евклідова норма:", norm_v)
print("Нормалізований вектор:", normalized_v)

Евклідова норма: 5.0
Нормалізований вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [32]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

# Знаходження векторного добутку
cross_product = np.cross(a, b)

print("Векторний добуток:", cross_product)

Векторний добуток: [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [33]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])

# Обчислення скалярного добутку та норм
dot_product = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

# Обчислення косинуса кута
cos_theta = dot_product / (norm_a * norm_b)

# Знаходження кута в радіанах за допомогою арккосинуса
angle_rad = np.arccos(cos_theta)

# Переведення радіанів у градуси
angle_deg = np.degrees(angle_rad)

print("Косинус кута:", cos_theta)
print("Кут у градусах:", angle_deg)

Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [34]:
# Код студента
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Спосіб 1: за допомогою атрибута .T
transposed_1 = A.T

# Спосіб 2: за допомогою функції np.transpose()
transposed_2 = np.transpose(A)

print("Транспонована матриця (через .T):\n", transposed_1)
print("\nТранспонована матриця (через np.transpose()):\n", transposed_2)

Транспонована матриця (через .T):
 [[1 4]
 [2 5]
 [3 6]]

Транспонована матриця (через np.transpose()):
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [35]:
# Код студента
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 2]
])

# 1. Поелементний добуток (A * B або матриця Адамара)
# При цій операції множаться елементи, що стоять на однакових позиціях.
# Наприклад: новий елемент [0,0] = A[0,0] * B[0,0] (1 * 2 = 2).
elementwise_product = A * B

# 2. Матричний добуток (A @ B або np.dot(A, B))
# Це класичне множення матриць з лінійної алгебри за правилом "рядок на стовпець".
# Кожен елемент результату — це сума добутків елементів рядка першої матриці
# на відповідні елементи стовпця другої матриці.
matrix_product = A @ B

print("Поелементний добуток (A * B):\n", elementwise_product)
print("\nМатричний добуток (A @ B):\n", matrix_product)

Поелементний добуток (A * B):
 [[2 0]
 [3 8]]

Матричний добуток (A @ B):
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [36]:
# Код студента
A = np.array([
    [4, 7],
    [2, 6]
])

# Обчислення визначника
determinant = np.linalg.det(A)

# Обчислення оберненої матриці
inverse_A = np.linalg.inv(A)

# Перевірка (множення оригінальної матриці на обернену)
verification = A @ inverse_A

print("Визначник:", determinant)
print("\nОбернена матриця:\n", inverse_A)

# Через особливості обчислень з плаваючою комою використовуємо np.round
# для коректного відображення нулів в одиничній матриці
print("\nРезультат множення A на обернену (одинична матриця):\n", np.round(verification))

Визначник: 10.000000000000002

Обернена матриця:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Результат множення A на обернену (одинична матриця):
 [[ 1. -0.]
 [ 0.  1.]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [37]:
# Код студента
# Матриця коефіцієнтів системи
A = np.array([
    [2, 1],
    [1, 3]
])

# Вектор правих частин
b = np.array([5, 6])

# Розв'язання системи
solution = np.linalg.solve(A, b)

print("Розв'язок системи [x, y]:", solution)
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")

Розв'язок системи [x, y]: [1.8 1.4]
x = 1.8
y = 1.4


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [38]:
# Код студента
# Створення одиничної матриці 4 × 4
I = np.eye(4)

# Створення довільної матриці 4 × 4 (наприклад, випадкові цілі числа)
A = np.random.randint(1, 10, (4, 4))

# Матричне множення довільної матриці на одиничну
result = A @ I

print("Одинична матриця I:\n", I)
print("\nПочаткова матриця A:\n", A)
print("\nРезультат множення A @ I:\n", result)

# Перевірка на співпадіння матриць
is_equal = np.array_equal(A, result)
print("\nЧи дорівнює результат початковій матриці (A == A @ I)?", is_equal)

Одинична матриця I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Початкова матриця A:
 [[2 5 1 6]
 [9 1 3 7]
 [4 9 3 5]
 [3 7 5 9]]

Результат множення A @ I:
 [[2. 5. 1. 6.]
 [9. 1. 3. 7.]
 [4. 9. 3. 5.]
 [3. 7. 5. 9.]]

Чи дорівнює результат початковій матриці (A == A @ I)? True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [39]:
# Код студента
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Додавання 10 до кожного елемента
result = A + 10

print("Результат:\n", result)

Результат:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [40]:
# Код студента
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

v = np.array([10, 20, 30])

result = A + v

print("Результат:\n", result)

Результат:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [41]:
# Код студента
A = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

# Обчислення середнього значення (μ) для кожного стовпця
mu = np.mean(A, axis=0)

# Обчислення стандартного відхилення (σ) для кожного стовпця
sigma = np.std(A, axis=0)

# Застосування формули нормалізації (завдяки broadcasting вектори
# mu та sigma автоматично застосовуються до кожного рядка матриці)
Z = (A - mu) / sigma

print("Середні значення стовпців (μ):", mu)
print("Стандартні відхилення стовпців (σ):", sigma)
print("\nНормалізована матриця (Z-оцінка):\n", Z)

Середні значення стовпців (μ): [20. 30. 40.]
Стандартні відхилення стовпців (σ): [8.16496581 8.16496581 8.16496581]

Нормалізована матриця (Z-оцінка):
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [42]:
# Код студента
# Встановлення seed для відтворюваності
np.random.seed(42)

# 1. 10 випадкових цілих чисел від 1 до 100 (включно)
random_ints = np.random.randint(1, 101, size=10)

# 2. Матриця 3 × 3 випадкових чисел від 0 до 1
random_matrix = np.random.rand(3, 3)

# 3. 1000 значень із стандартного нормального розподілу (середнє 0, відхилення 1)
normal_values = np.random.randn(1000)
# Також можна використати: np.random.normal(loc=0.0, scale=1.0, size=1000)

# Обчислення середнього та стандартного відхилення для нормального розподілу
mean_val = np.mean(normal_values)
std_val = np.std(normal_values)

print("10 випадкових цілих чисел:\n", random_ints)
print("\nМатриця 3 × 3 випадкових чисел (0-1):\n", random_matrix)
print("\nСтатистика для 1000 значень з нормального розподілу:")
print("Середнє значення:", mean_val)
print("Стандартне відхилення:", std_val)

10 випадкових цілих чисел:
 [52 93 15 72 61 21 83 87 75 75]

Матриця 3 × 3 випадкових чисел (0-1):
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]

Статистика для 1000 значень з нормального розподілу:
Середнє значення: 0.02216865975826456
Стандартне відхилення: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [43]:
# Код студента
# Моделювання оцінок 30 студентів (від 0 до 100 включно)
grades = np.random.randint(0, 101, size=30)

# Обчислення показників
mean_grade = np.mean(grades)
median_grade = np.median(grades)
max_grade = np.max(grades)
min_grade = np.min(grades)

# Підрахунок кількості та відсотка за допомогою булевих масок
passed_count = np.sum(grades >= 60)
excellent_percent = np.mean(grades >= 90) * 100  # np.mean від булевої маски дає частку

print("Оцінки студентів:\n", grades)
print("\nСередня оцінка:", mean_grade)
print("Медіана:", median_grade)
print("Найвища оцінка:", max_grade)
print("Найнижча оцінка:", min_grade)
print("Кількість студентів з оцінкою >= 60:", passed_count)
print(f"Відсоток студентів з оцінкою >= 90: {excellent_percent:.1f}%")

Оцінки студентів:
 [25  2 40 59 13 74 81 11 86 11 12 24 44 18 54 99 44  7 92 52 54 31 50 43
 81 69 17 82 21 36]

Середня оцінка: 44.4
Медіана: 43.5
Найвища оцінка: 99
Найнижча оцінка: 2
Кількість студентів з оцінкою >= 60: 8
Відсоток студентів з оцінкою >= 90: 6.7%


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [44]:
# Код студента
sales = np.array([
    [120, 150, 170, 160],
    [80,   90, 100, 110],
    [200, 180, 210, 230]
])

# 1. Загальний обсяг продажів кожного товару (сума по рядках, axis=1)
total_per_product = np.sum(sales, axis=1)

# 2. Загальний обсяг продажів у кожному місяці (сума по стовпцях, axis=0)
total_per_month = np.sum(sales, axis=0)

# 3. Товар із найбільшими сумарними продажами
# np.argmax() повертає індекс максимального елемента. Додаємо 1 для людської нумерації
best_product_idx = np.argmax(total_per_product) + 1

# 4. Місяць із найбільшим загальним обсягом продажів
best_month_idx = np.argmax(total_per_month) + 1

# 5. Середній обсяг продажів кожного товару
avg_per_product = np.mean(sales, axis=1)

print("Загальний обсяг продажів кожного товару:", total_per_product)
print("Загальний обсяг продажів у кожному місяці:", total_per_month)
print(f"Товар із найбільшими сумарними продажами: Товар №{best_product_idx}")
print(f"Місяць із найбільшим загальним обсягом продажів: Місяць №{best_month_idx}")
print("Середній обсяг продажів кожного товару:", avg_per_product)

Загальний обсяг продажів кожного товару: [600 380 820]
Загальний обсяг продажів у кожному місяці: [400 420 480 500]
Товар із найбільшими сумарними продажами: Товар №3
Місяць із найбільшим загальним обсягом продажів: Місяць №4
Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [45]:
# Код студента
# Створення матриці 5 × 5 із випадкових цілих чисел від 1 до 20 (включно)
matrix = np.random.randint(1, 21, size=(5, 5))
print("Початкова матриця:\n", matrix)

# 1. Сума головної діагоналі (можна використати np.trace або np.sum(np.diag()))
main_diag_sum = np.trace(matrix)

# 2. Сума побічної діагоналі
# (np.fliplr віддзеркалює матрицю зліва направо, перетворюючи побічну діагональ на головну)
anti_diag_sum = np.trace(np.fliplr(matrix))

# 3. Максимальний елемент кожного рядка (axis=1)
max_per_row = np.max(matrix, axis=1)

# 4. Мінімальний елемент кожного стовпця (axis=0)
min_per_col = np.min(matrix, axis=0)

# Обчислення середнього значення всієї матриці
mean_val = np.mean(matrix)

print("\nСума головної діагоналі:", main_diag_sum)
print("Сума побічної діагоналі:", anti_diag_sum)
print("Максимальні елементи рядків:", max_per_row)
print("Мінімальні елементи стовпців:", min_per_col)
print("Середнє значення матриці:", mean_val)

# 5. Заміна всіх елементів, менших за середнє значення, на 0
matrix[matrix < mean_val] = 0

print("\nМатриця після заміни елементів:\n", matrix)

Початкова матриця:
 [[ 9  3 10 19  3]
 [15  1  7 12 17]
 [20  5  4 12 20]
 [18 17 19  9  4]
 [ 2  4  2 15  2]]

Сума головної діагоналі: 25
Сума побічної діагоналі: 38
Максимальні елементи рядків: [19 17 20 19 15]
Мінімальні елементи стовпців: [2 1 2 9 2]
Середнє значення матриці: 9.96

Матриця після заміни елементів:
 [[ 0  0 10 19  0]
 [15  0  0 12 17]
 [20  0  0 12 20]
 [18 17 19  0  0]
 [ 0  0  0 15  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [46]:
# Код студента
X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [5, 7, 9]
])

# Отримання окремих рядків (індексація починається з 0)
row1 = X[0]
row2 = X[1]
row3 = X[2]

# Обчислення евклідової відстані між рядками
dist_1_2 = np.linalg.norm(row1 - row2)
dist_1_3 = np.linalg.norm(row1 - row3)
dist_2_3 = np.linalg.norm(row2 - row3)

print("Відстань між 1-м і 2-м рядком:", dist_1_2)
print("Відстань між 1-м і 3-м рядком:", dist_1_3)
print("Відстань між 2-м і 3-м рядком:", dist_2_3)

Відстань між 1-м і 2-м рядком: 1.7320508075688772
Відстань між 1-м і 3-м рядком: 5.196152422706632
Відстань між 2-м і 3-м рядком: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [47]:
# Код студента
# Створення матриці 4 × 4 із довільних цілих чисел
matrix = np.random.randint(1, 20, size=(4, 4))
print("Початкова матриця:\n", matrix)

# Обчислення норми кожного рядка.
# Використовуємо keepdims=True, щоб результат мав форму (4, 1) замість (4,).
# Це дозволить NumPy правильно застосувати broadcasting при діленні.
row_norms = np.linalg.norm(matrix, axis=1, keepdims=True)
print("\nНорми рядків:\n", row_norms)

# Нормалізація рядків до одиничної довжини (ділення кожного елемента на норму його рядка)
normalized_matrix = matrix / row_norms

print("\nНормалізована матриця (кожен рядок має одиничну довжину):\n", normalized_matrix)

# Перевірка: обчислимо норми рядків нової матриці (вони мають дорівнювати 1)
check_norms = np.linalg.norm(normalized_matrix, axis=1)
print("\nПеревірка (норми нових рядків):", check_norms)

Початкова матриця:
 [[ 4  6  7 10]
 [19 19 12  3]
 [13 18  8 15]
 [ 1  3  8  4]]

Норми рядків:
 [[14.17744688]
 [29.58039892]
 [27.96426291]
 [ 9.48683298]]

Нормалізована матриця (кожен рядок має одиничну довжину):
 [[0.28213825 0.42320737 0.49374193 0.70534562]
 [0.64231723 0.64231723 0.40567404 0.10141851]
 [0.46487905 0.64367869 0.28607942 0.5363989 ]
 [0.10540926 0.31622777 0.84327404 0.42163702]]

Перевірка (норми нових рядків): [1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [48]:
# Код студента
# Матриця коефіцієнтів системи (A)
A = np.array([
    [1,  2,  1],
    [2,  1, -1],
    [3, -1,  2]
])

# Вектор правих частин (b)
b = np.array([9, 8, 3])

# Розв'язання системи
x = np.linalg.solve(A, b)

# Перевірка: множення матриці коефіцієнтів на знайдений розв'язок
verification = A @ x

# Порівняння результату з вектором b.
# Використовуємо np.allclose() замість звичайного == (або np.array_equal)
# для коректного порівняння чисел із плаваючою комою.
is_correct = np.allclose(verification, b)

print("Розв'язок системи [x, y, z]:", np.round(x, 2))
print("\nПеревірка (A @ x):", np.round(verification, 2))
print("Оригінальний вектор b:", b)
print("Чи збігається результат (з урахуванням похибки заокруглення)?", is_correct)

Розв'язок системи [x, y, z]: [ 2.22  3.44 -0.11]

Перевірка (A @ x): [9. 8. 3.]
Оригінальний вектор b: [9 8 3]
Чи збігається результат (з урахуванням похибки заокруглення)? True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
